packageExtensions:
  '@firebase/analytics-compat@^0.2.4':
    peerDependencies:
      '@firebase/app': '0.x'
  '@firebase/app-check-compat@^0.3.4':
    peerDependencies:
      '@firebase/app': '0.x'
  '@firebase/auth-compat@^0.3.4':
    peerDependencies:
      '@firebase/app': '0.x'
      '@firebase/app-types': '^0.x'
  '@firebase/firestore-compat@^0.3.4':
    peerDependencies:
      '@firebase/app': '0.x'
      '@firebase/app-types': '^0.x'
  '@firebase/functions-compat@^0.3.4':
    peerDependencies:
      '@firebase/app': '0.x'
  '@firebase/installations-compat@^0.2.4':
    peerDependencies:
      '@firebase/app': '0.x'
      '@firebase/app-types': '^0.x'
  '@firebase/messaging-compat@^0.2.4':
    peerDependencies:
      '@firebase/app': '0.x'
  '@firebase/performance-compat@^0.2.4':
    peerDependencies:
      '@firebase/app': '0.x'
  '@firebase/remote-config-compat@^0.2.4':
    peerDependencies:
      '@firebase/app': '0.x'
  '@firebase/storage-compat@^0.3.2':
    peerDependencies:
      '@firebase/app': '0.x'
      '@firebase/app-types': '^0.x'
  '@storybook/addon-styling@^0.3.1':
    dependencies:
      '@storybook/addons': '^6.5.8'
      '@storybook/api': '^6.5.8'
      '@storybook/components': '^6.5.8'
      '@storybook/core-events': '^6.5.8'
      '@storybook/theming': '^6.5.8'
      '@storybook/manager-api': '^7.0.0-beta.56'
  'styled-components@^5.3.6':
    dependencies:
      'react-is': '>= 16.8.0'
  'babel-loader@^9.1.2':
    dependencies:
      webpack: '>=5'
